spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ai-bookstore-crud
    username: username
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

#used to see the parameters of the queries
logging.level.org.hibernate:
  orm.jdbc.bind: TRACE
  type: TRACE
  stat: TRACE